apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 16
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx-test
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/os-release
          initialDelaySeconds: 30
          periodSeconds: 5
