apiVersion: apps/v1
kind: Deployment
metadata:
  name: truecommand-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: truecommand-test
  template:
    metadata:
      labels:
        app: truecommand-test
    spec:
      containers:
      - image: docker.io/ixsystems/truecommand
        name: truecommand-test
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/os-release
          initialDelaySeconds: 30
          periodSeconds: 5
